# Generated by Django 5.0.14 on 2026-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='statut',
            field=models.CharField(choices=[('freelance', 'Freelance'), ('pme', 'PME'), ('entreprise', 'Entreprise')], max_length=50),
        ),
    ]
