# Generated by Django 6.0.1 on 2026-01-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
        ('users', '0003_alter_customuser_id'),
    ]

    operations = [
    ]
