# Generated by Django 5.0.14 on 2026-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_birth_date_client_province_client_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('province1', 'Antananarivo'), ('province2', 'Antsiranana'), ('province3', 'Toamasina'), ('province3', 'Mahajanga'), ('province3', 'Fianarantsoa'), ('province3', 'Toliara')], max_length=50, null=True),
        ),
    ]
