# Generated by Django 5.0.14 on 2026-01-16 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='client',
            name='age_range',
            field=models.CharField(blank=True, choices=[('<18', 'Moins de 18 ans'), ('18-25', '18-25 ans'), ('26-35', '26-35 ans'), ('36-50', '36-50 ans'), ('50+', 'Plus de 50 ans')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('province1', 'Antananarivo'), ('province2', 'Antsiranana'), ('province3', 'Toamasina'), ('province4', 'Mahajanga'), ('province5', 'Fianarantsoa'), ('province6', 'Toliara')], max_length=50, null=True),
        ),
    ]
