# Generated by Django 5.0.14 on 2026-01-16 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_client_birth_date_client_age_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
