# Generated by Django 6.0.1 on 2026-01-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
